version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: SubAppDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  subscriptionapp:
    build:
      context: .
      dockerfile: SubscriptionApp/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=SubAppDb;Username=postgres;Password=postgres
      Redis__Connection: redis:6379
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
volumes:
  postgres_data: